### ISSUE TITLE
Add tests to prove correct messages are being generated

### ISSUE THREAD

**Issue by jeddy3** [hudochenkov/stylelint-property-groups-structure#2]
Related to https://github.com/hudochenkov/stylelint-property-groups-structure/issues/1

When looking through the tests I couldn't see any that tested the generation of the correct messages.

Do you think it'd be prudent to added a few?

**Comment by hudochenkov** [comment]
Sounds reasonable and definitely needed in tests.

**Comment by hudochenkov** [comment]
Now it's covered :)
